import { useEffect } from "react";
import { ArrowUpRight, MapPin, Phone } from "lucide-react";
import { Header, Footer, CTA, WhatsAppLink, CallLink } from "@/components/Vistara";
import { MessageCircle } from "lucide-react";
import { Link } from "wouter";

export default function Contact() {
  useEffect(() => { document.title = "Contact Vistara Interior | Book a Design Consultation"; document.querySelector('meta[name="description"]')?.setAttribute("content", "Book a free design consultation in Bengaluru. We walk your site, listen, and come back with a point of view — reach Vistara on WhatsApp or by phone."); }, []);
  return <div className="page-shell"><Header /><main>
    <section className="container grid gap-12 pb-20 pt-16 md:grid-cols-[1fr_.9fr] md:items-end md:pb-28 md:pt-24"><div><p className="eyebrow">BENGALURU · START WITH A CONVERSATION</p><h1 className="display mt-5 max-w-[650px] text-[clamp(60px,9vw,126px)]">Tell us about your space.</h1><p className="mt-8 max-w-[530px] text-[18px] leading-7 text-[var(--muted-ink)]">A consultation costs nothing — we walk the site, listen, and come back with a point of view.</p></div><div className="image-frame aspect-[4/3]"><img src="/images/board.webp" alt="material board with oak veneer, verde marble and brushed brass — Vistara Interior studio" /></div></section>
    <section className="section-pad bg-[var(--limewash)]"><div className="container grid gap-12 md:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Choose your route</p><h2 className="display mt-4 text-[clamp(45px,6vw,78px)]">Let’s talk space.</h2></div><div className="grid gap-4 sm:grid-cols-3"><WhatsAppLink className="group oak-rule rounded-[14px] bg-[var(--fern)] p-6 text-[var(--gesso)] transition-transform hover:-translate-y-1 text-left w-full" variant="card"><MessageCircle size={18} className="text-[var(--oak)]" /><p className="mt-10 text-[18px] font-semibold text-[var(--gesso)]">WhatsApp us</p><p className="mt-2 text-[13px] text-[var(--gesso)]/65">Start with a message.</p></WhatsAppLink><CallLink className="group oak-rule rounded-[14px] bg-[var(--fern)] p-6 text-[var(--gesso)] transition-transform hover:-translate-y-1 text-left w-full"><Phone size={18} className="text-[var(--oak)]" /><p className="mt-10 text-[18px] font-semibold text-[var(--gesso)]">Call us</p><p className="mt-2 text-[13px] text-[var(--gesso)]/65">Speak to the studio.</p></CallLink><Link href="/contact" className="group oak-rule rounded-[14px] bg-[var(--fern)] p-6 text-[var(--gesso)] transition-transform hover:-translate-y-1"><ArrowUpRight size={18} className="text-[var(--oak)]" /><p className="mt-10 text-[18px] font-semibold text-[var(--gesso)]">Book a consultation</p><p className="mt-2 text-[13px] text-[var(--gesso)]/65">A point of view, not a package.</p></Link></div></div></section>
    <section className="section-pad"><div className="container grid gap-12 md:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Find the studio</p><h2 className="display mt-4 text-[clamp(45px,6vw,78px)]">Here, when you’re ready.</h2></div><div className="grid gap-6 md:grid-cols-2"><div className="rounded-[14px] border border-[var(--line)] bg-[var(--limewash)] p-7"><MapPin className="text-[var(--fern)]" size={20} /><div className="mt-6 space-y-5"><p className="text-[16px] leading-7">85, Ayyappa Block, Kogilu,<br />Yelahanka, Bangalore 560064</p><div className="border-t border-[var(--line)] pt-5"><p className="mono text-[10px] tracking-[.15em] text-[var(--brass)]">CALL / WHATSAPP</p><a href="tel:+919964649595" className="mt-2 block text-[18px] font-semibold text-[var(--fern)] hover:text-[var(--fern-deep)] transition-colors">+91 99646 49595</a></div></div></div><div className="overflow-hidden rounded-[14px]"><iframe src="https://maps.google.com/maps?q=85+Ayyappa+Block+Kogilu+Yelahanka+Bangalore+560064&t=&z=15&ie=UTF8&iwloc=&output=embed" width="100%" height="280" style={{border: 0}} allowFullScreen loading="lazy" referrerPolicy="no-referrer-when-downgrade" title="Vistara Interior location" /></div></div></div></section>
    <section className="section-pad bg-[var(--limewash)]"><div className="container grid gap-12 md:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">What happens next</p><h2 className="display mt-4 text-[clamp(45px,6vw,78px)]">Three considered moves.</h2></div><div className="grid sm:grid-cols-3">{["We call you back — [TBC window]", "We walk your site and listen", "You get a point of view, not a package"].map((step, i) => <div key={step} className="oak-rule min-h-[160px] p-5"><p className="mono text-[var(--brass)]">0{i + 1}</p><p className="mt-7 text-[18px] leading-6">{step}</p></div>)}</div></div></section>
    <CTA label="Book a consultation" />
  </main><Footer /></div>;
}
