import { useEffect, useState } from "react";
import { Link } from "wouter";
import { ArrowDownRight, ArrowUpRight, Check, ChevronDown } from "lucide-react";
import { Header, Footer, CTA, FAQ, ProjectCard, images } from "@/components/Vistara";

const homeFaq: [string, string][] = [
  ["What does Vistara Interior do?", "Vistara Interior designs and builds complete interiors — villa homes on one side, workspaces on the other."],
  ["Do you have your own factory?", "Yes — every piece is made in our own factory, with no outsourcing and everything custom-built in-house."],
  ["Do you work with both homes and workspaces?", "Yes — Vistara Interior serves premium residential homes and commercial or corporate workspaces."],
  ["How do we begin?", "A consultation costs nothing — we walk the site, listen, and come back with a point of view."]
];

export default function Home() {
  const [showcase, setShowcase] = useState<"residential" | "commercial">("residential");
  const residentialProjects = [{ title: "Whitefield Villa", spec: "WHITEFIELD VILLA · 4,200 SQ FT · TURNKEY · 2025", image: images.whitefield, alt: "oak-panelled living room with ivory seating — villa, Whitefield" }, { title: "Indiranagar Apartment", spec: "INDIRANAGAR APARTMENT · [SAMPLE] · TURNKEY · 2025", image: images.indiranagar, alt: "living and dining room with oak built-ins — apartment, Indiranagar" }, { title: "Sarjapur Villa", spec: "SARJAPUR VILLA · [SAMPLE] · TURNKEY · 2025", image: images.sarjapur, alt: "sunlit villa lounge opening to a courtyard — villa, Sarjapur" }];
  const commercialProjects = [{ title: "HSR Office", spec: "HSR OFFICE · [SAMPLE] · TURNKEY · 2025", image: images.hsr, alt: "corporate office with oak acoustic wall and glass meeting room — office, HSR" }, { title: "Koramangala F&B", spec: "KORAMANGALA F&B · [SAMPLE] · TURNKEY · 2025", image: images.koramangala, alt: "restaurant interior with oak banquette and brushed brass lighting — F&B, Koramangala" }, { title: "MG Road Retail", spec: "MG ROAD RETAIL · [SAMPLE] · TURNKEY · 2025", image: images.mgroad, alt: "boutique retail interior with oak display wall — retail, MG Road" }];
  useEffect(() => { document.title = "Interior Designers in Bengaluru | Vistara Interior"; const meta = document.querySelector('meta[name="description"]'); meta?.setAttribute("content", "Bengaluru interior design & turnkey fit-outs with our own factory. Villa homes and corporate workspaces — one team from sketch to handover, 15+ years."); }, []);
  return <div className="page-shell"><Header /><main>
    <section className="container grid gap-12 pb-20 pt-14 md:grid-cols-[.82fr_1.18fr] md:items-center md:pb-28 md:pt-20"><div className="reveal max-w-[570px]"><p className="eyebrow">BENGALURU · INTERIORS & TURNKEY FIT-OUTS</p><h1 className="display mt-5 text-[clamp(58px,8vw,112px)]">Warmth for your home. <em className="text-[var(--fern)]">Precision</em> for your workplace.</h1><p className="mt-8 max-w-[525px] text-[17px] leading-7 text-[var(--muted-ink)]">Vistara Interior designs and builds complete interiors — villa homes on one side, workspaces for HP, Tata and Oracle on the other. Every piece made in our own factory. One team from first sketch to handover, for 15+ years.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/home-interiors-bangalore" className="button-fern">For your home <ArrowUpRight size={15} /></Link><Link href="/commercial-interior-designers-bangalore" className="button-fern">For your workspace <ArrowUpRight size={15} /></Link></div></div><div className="relative"><div className="image-frame aspect-[4/3] md:aspect-[5/4]"><img src={images.hero} alt="living room with oak veneer panelling — villa, Whitefield" /></div><div className="absolute -bottom-6 left-5 max-w-[230px] rounded-[14px] bg-[var(--fern)] p-5 text-[var(--gesso)] shadow-xl md:-left-8"><span className="mono text-[var(--oak)]">IN-HOUSE CRAFT</span><p className="mt-3 font-display text-[22px] leading-tight">Made in our factory, not ordered from a catalogue.</p></div><span className="mono absolute right-3 top-3 bg-[var(--gesso)]/85 px-2 py-1 text-[var(--fern)]">01 / 04</span></div></section>
    <section className="border-y border-[var(--line)] bg-[var(--limewash)]"><div className="container grid gap-8 py-8 md:grid-cols-[.8fr_1.2fr] md:items-center"><p className="mono text-[var(--fern)]">15+ years · own factory · one team</p><p className="max-w-[650px] text-[15px] leading-6 text-[var(--muted-ink)]">The standards corporate India demands — brought home. Material portfolio wider than mainstream catalogues. Turnkey one-team delivery.</p></div></section>
    <section className="section-pad"><div className="container grid gap-12 md:grid-cols-[.75fr_1.25fr] md:items-start"><div><p className="eyebrow">The Vistara difference</p><h2 className="display mt-4 text-[clamp(44px,6vw,78px)]">Designed here.<br /><em className="text-[var(--fern)]">Built here.</em></h2></div><div className="grid gap-8 md:grid-cols-2"><div className="image-frame aspect-[4/5]"><img src={images.board} alt="material board with oak veneer and verde marble — Vistara Interior factory" /></div><div className="flex flex-col justify-end"><p className="text-[18px] leading-7">Your home and your workplace need different answers. The standard of making them should not change.</p><div className="mt-8 space-y-4 text-[14px] text-[var(--muted-ink)]"><p className="flex gap-3"><Check className="mt-0.5 shrink-0 text-[var(--fern)]" size={17} />own factory, no outsourcing, everything custom-built in-house</p><p className="flex gap-3"><Check className="mt-0.5 shrink-0 text-[var(--fern)]" size={17} />material portfolio wider than mainstream catalogues</p><p className="flex gap-3"><Check className="mt-0.5 shrink-0 text-[var(--fern)]" size={17} />turnkey one-team delivery</p></div></div></div></div></section>
    <section className="section-pad bg-[var(--limewash)]"><div className="container"><div className="mb-10 flex flex-col items-start justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow">Selected work · [SAMPLE]</p><h2 className="display mt-4 max-w-[760px] text-[clamp(46px,6vw,82px)]">Homes and workspaces, held to one standard.</h2></div><div className="flex rounded-full border border-[var(--line)] bg-[var(--gesso)] p-1.5"><button type="button" onClick={() => setShowcase("residential")} className={`rounded-full px-6 py-2.5 text-[14px] font-semibold transition-colors ${showcase === "residential" ? "bg-[var(--fern)] text-[var(--gesso)]" : "text-[var(--muted-ink)]"}`}>Residential</button><button type="button" onClick={() => setShowcase("commercial")} className={`rounded-full px-6 py-2.5 text-[14px] font-semibold transition-colors ${showcase === "commercial" ? "bg-[var(--fern)] text-[var(--gesso)]" : "text-[var(--muted-ink)]"}`}>Commercial</button></div></div><div className="mb-8 flex flex-wrap items-center justify-between gap-4"><div className="flex flex-wrap gap-3"><span className="chip factory">{showcase === "residential" ? "Residential interiors" : "Commercial & corporate"}</span><span className="chip">{showcase === "residential" ? "Villa homes · Fine apartments" : "Office · Retail · F&B"}</span></div><Link href={showcase === "residential" ? "/home-interiors-bangalore" : "/commercial-interior-designers-bangalore"} className="text-[13px] font-semibold text-[var(--fern)] underline decoration-[var(--oak)] underline-offset-4">View {showcase === "residential" ? "residential" : "workspace"} work <ArrowUpRight size={14} className="inline" /></Link></div><div className="grid gap-10 md:grid-cols-3">{(showcase === "residential" ? residentialProjects : commercialProjects).map((project, index) => <ProjectCard key={project.title} index={index} project={project} />)}</div></div></section>
    <section className="section-pad bg-[var(--limewash)]"><div className="container grid gap-12 md:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">How it works</p><h2 className="display mt-4 text-[clamp(46px,6vw,80px)]">One team.<br /><em className="text-[var(--fern)]">Four moves.</em></h2></div><div className="grid sm:grid-cols-2">{["First sketch", "Material board", "Factory build", "Handover"].map((step, i) => <div key={step} className="oak-rule min-h-[145px] p-5"><p className="mono text-[var(--brass)]">0{i + 1}</p><h3 className="display mt-6 text-[30px]">{step}</h3></div>)}</div></div></section>
    <section className="section-pad"><div className="container grid gap-12 md:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">A word from the work</p><h2 className="display mt-4 text-[clamp(44px,5vw,70px)]">Proof over adjectives.</h2></div><div className="grid gap-8 md:grid-cols-2"><blockquote className="border-l-2 border-[var(--oak)] pl-6"><p className="display text-[28px] leading-tight">They didn't just design our home — they understood how we live in it. Every corner feels intentional.</p><footer className="mono mt-6 text-[var(--muted-ink)]">Priya & Arjun · Whitefield</footer></blockquote><blockquote className="border-l-2 border-[var(--oak)] pl-6"><p className="display text-[28px] leading-tight">The quality of their factory work is something you can feel the moment you touch the finish. Nothing off the shelf comes close.</p><footer className="mono mt-6 text-[var(--muted-ink)]">Meera K. · Indiranagar</footer></blockquote></div></div></section>
    <section className="section-pad bg-[var(--limewash)]"><div className="container grid gap-12 md:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Questions, answered</p><h2 className="display mt-4 text-[clamp(44px,5vw,70px)]">FAQ</h2></div><FAQ items={homeFaq} /></div></section>
    <CTA />
  </main><Footer /></div>;
}
